// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9QJros4eO01jLhJ1bazXYAe6UTqiokVA',
    appId: '1:386970740165:android:7fced4359c7730982b17ac',
    messagingSenderId: '386970740165',
    projectId: 'net-startupworx-blocks',
    storageBucket: 'net-startupworx-blocks.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgSAG7HRsmcfDAmhz_yMGiGigh9XbixqU',
    appId: '1:386970740165:ios:482653d6fdc5e6562b17ac',
    messagingSenderId: '386970740165',
    projectId: 'net-startupworx-blocks',
    storageBucket: 'net-startupworx-blocks.appspot.com',
    iosClientId: '386970740165-e3eqajjej7dfn3ip1b3sf0sf5hgicq9f.apps.googleusercontent.com',
    iosBundleId: 'net.startupworx.blocks',
  );
}
